### ISSUE TITLE
What is this for?

### ISSUE THREAD

**Issue by jzabroski** [YoloDev/YoloDev.Fake.Tool.Docker#1]

**Comment by Alxandr** [comment]
Buildkit is not a replacement for docker, rather it's a tool for creating (amongst other things) docker compatible images. Docker is slated to use buildkit internally eventually. But if you want to do some niche things like creating multi platform images, it's much easier using buildkit directly (after you've managed to set it up, which can be painful).

**Comment by jzabroski** [comment]
Yes, I did understand that part.  Thanks for being so considerate to explain it, though.  Really nice of you!

**Comment by Alxandr** [comment]
Yeah, no problem. How did you end up here btw?

**Comment by jzabroski** [comment]
I don't remember.  Someone once called me the Human Hidden Markov because I have completely blackbox explanations for how and why I learn things at times.  I'm trying to get better about "separating the pearls from the swine waste" and systematizing my learning, which is what my Home GitHub is all about.  If you comb through it you will see an ever-expanding set of topics and my deep, intricate, semi-memorized knowledge of those topics.

**Comment by Alxandr** [comment]
I ment how did you stumble across this repository :P

**Comment by jzabroski** [comment]
That's what I mean... I'm not sure.... Here is my Chrome History:

![image](https://user-images.githubusercontent.com/447485/55817578-d1b58400-5ac2-11e9-93f0-da208ccb2dd0.png)

**Comment by jzabroski** [comment]
After that, I landed on your repository.  I don't remember how.  I just explore like a corydoras - a type of fish that likes exploring caves and tunnels 🐟

**Comment by jzabroski** [comment]
Ah.  Now I remember.  I follow F# Expecto library and you or someone mentioned a comment about https://github.com/YoloDev/YoloDev.Expecto.TestSdk

**Comment by Alxandr** [comment]
Yep. That makes sense timing wise, as we're currently working on fixing an issue there.
